// Real flight hardware, real names, published (approximate) specs.
// Thrust in N, Isp in s, masses in kg. Where a figure is not officially
// published (e.g. BE-4), values are widely-cited estimates — the blurbs say so.
// Adding a part = adding one entry here; the VAB picks it up automatically.

import type { EngineSpec } from './engine';
import type { PayloadSpec } from './payload';
import type { Fairing, RocketDesign, StageSpec } from './rocket';
import { Q_MAX_DEFAULT } from '../constants';

export const ENGINES: Record<string, EngineSpec> = {
  'merlin-1d': {
    id: 'merlin-1d',
    name: 'Merlin 1D',
    thrustSL: 845e3,
    thrustVac: 914e3,
    ispSL: 283,
    ispVac: 311,
    blurb: 'SpaceX’s kerolox workhorse — nine of them lift every Falcon 9.',
  },
  'merlin-vac': {
    id: 'merlin-vac',
    name: 'Merlin Vacuum',
    thrustSL: 0,
    thrustVac: 934e3,
    ispSL: 0,
    ispVac: 348,
    blurb: 'Merlin with a huge radiatively-cooled nozzle. Space only.',
  },
  'raptor-2': {
    id: 'raptor-2',
    name: 'Raptor 2',
    thrustSL: 2256e3,
    thrustVac: 2450e3,
    ispSL: 327,
    ispVac: 353,
    blurb: 'Full-flow staged-combustion methalox. 33 of these lift Super Heavy.',
  },
  'raptor-vac': {
    id: 'raptor-vac',
    name: 'Raptor Vacuum',
    thrustSL: 0,
    thrustVac: 2400e3,
    ispSL: 0,
    ispVac: 372,
    blurb: 'Vacuum Raptor for Starship’s upper stage (figures estimated).',
  },
  'rs-25': {
    id: 'rs-25',
    name: 'RS-25 (SSME)',
    thrustSL: 1860e3,
    thrustVac: 2279e3,
    ispSL: 366,
    ispVac: 452,
    blurb: 'The Space Shuttle Main Engine — hydrolox, astonishing efficiency, now on SLS.',
  },
  'f-1': {
    id: 'f-1',
    name: 'F-1',
    thrustSL: 6770e3,
    thrustVac: 7770e3,
    ispSL: 263,
    ispVac: 304,
    blurb: 'The Saturn V monster — still the most powerful single-chamber engine ever flown.',
  },
  'j-2': {
    id: 'j-2',
    name: 'J-2',
    thrustSL: 0,
    thrustVac: 1033e3,
    ispSL: 0,
    ispVac: 421,
    blurb: 'Hydrolox upper-stage engine that pushed Apollo toward the Moon.',
  },
  'rd-180': {
    id: 'rd-180',
    name: 'RD-180',
    thrustSL: 3830e3,
    thrustVac: 4150e3,
    ispSL: 311,
    ispVac: 338,
    blurb: 'Russian twin-chamber kerolox masterpiece that powered Atlas V.',
  },
  'rd-191': {
    id: 'rd-191',
    name: 'RD-191',
    thrustSL: 1920e3,
    thrustVac: 2090e3,
    ispSL: 311,
    ispVac: 337,
    blurb: 'Single-chamber descendant of the RD-170 family, flies on Angara.',
  },
  'nk-33': {
    id: 'nk-33',
    name: 'NK-33',
    thrustSL: 1510e3,
    thrustVac: 1638e3,
    ispSL: 297,
    ispVac: 331,
    blurb: 'Built for the Soviet N1 Moon rocket; decades later it flew again on Antares.',
  },
  'rs-68a': {
    id: 'rs-68a',
    name: 'RS-68A',
    thrustSL: 3140e3,
    thrustVac: 3560e3,
    ispSL: 362,
    ispVac: 412,
    blurb: 'The largest hydrolox engine ever flown — Delta IV’s big orange flame.',
  },
  'be-4': {
    id: 'be-4',
    name: 'BE-4',
    thrustSL: 2400e3,
    thrustVac: 2600e3,
    ispSL: 310,
    ispVac: 340,
    blurb: 'Blue Origin methalox; powers Vulcan and New Glenn (figures estimated).',
  },
  'vulcain-2': {
    id: 'vulcain-2',
    name: 'Vulcain 2',
    thrustSL: 935e3,
    thrustVac: 1390e3,
    ispSL: 318,
    ispVac: 431,
    blurb: 'Ariane 5’s hydrolox core engine — needs solid boosters to leave the pad.',
  },
  'hm7b': {
    id: 'hm7b',
    name: 'HM7B',
    thrustSL: 0,
    thrustVac: 62.7e3,
    ispSL: 0,
    ispVac: 446,
    blurb: 'Small, veteran hydrolox upper-stage engine of the Ariane family.',
  },
  vikas: {
    id: 'vikas',
    name: 'Vikas',
    thrustSL: 725e3,
    thrustVac: 800e3,
    ispSL: 262,
    ispVac: 293,
    blurb: 'ISRO’s hypergolic workhorse — the muscle of PSLV and GSLV.',
  },
  'ce-20': {
    id: 'ce-20',
    name: 'CE-20',
    thrustSL: 0,
    thrustVac: 200e3,
    ispSL: 0,
    ispVac: 443,
    blurb: 'India’s cryogenic upper-stage engine — flew Chandrayaan-3 on LVM3.',
  },
  s139: {
    id: 's139',
    name: 'S139 solid motor',
    thrustSL: 4800e3,
    thrustVac: 5000e3,
    ispSL: 237,
    ispVac: 269,
    blurb: 'PSLV’s big solid first stage. Once lit, there is no off switch.',
  },
  'srb-shuttle': {
    id: 'srb-shuttle',
    name: 'Shuttle SRB',
    thrustSL: 12500e3,
    thrustVac: 13800e3,
    ispSL: 242,
    ispVac: 268,
    blurb: 'The Space Shuttle’s solid boosters — the most powerful motors ever flown.',
  },
  'yf-100': {
    id: 'yf-100',
    name: 'YF-100',
    thrustSL: 1200e3,
    thrustVac: 1340e3,
    ispSL: 300,
    ispVac: 335,
    blurb: 'China’s staged-combustion kerolox engine, core of the Long March family.',
  },
  rutherford: {
    id: 'rutherford',
    name: 'Rutherford',
    thrustSL: 24.9e3,
    thrustVac: 25.8e3,
    ispSL: 280,
    ispVac: 311,
    blurb: 'Rocket Lab’s 3D-printed, battery-pumped engine — nine per Electron.',
  },
  'rutherford-vac': {
    id: 'rutherford-vac',
    name: 'Rutherford Vacuum',
    thrustSL: 0,
    thrustVac: 25.8e3,
    ispSL: 0,
    ispVac: 343,
    blurb: 'The vacuum-nozzle Rutherford on Electron’s second stage.',
  },
  kestrel: {
    id: 'kestrel',
    name: 'Kestrel',
    thrustSL: 0,
    thrustVac: 31e3,
    ispSL: 0,
    ispVac: 317,
    blurb: 'Falcon 1’s tiny pressure-fed upper-stage engine — where SpaceX began.',
  },
  'rl10b-2': {
    id: 'rl10b-2',
    name: 'RL10B-2',
    thrustSL: 0,
    thrustVac: 110e3,
    ispSL: 0,
    ispVac: 466,
    blurb: 'The most efficient chemical engine in service — hydrolox perfection since 1963.',
  },
  'star-48b': {
    id: 'star-48b',
    name: 'Star 48B',
    thrustSL: 0,
    thrustVac: 66e3,
    ispSL: 0,
    ispVac: 286,
    blurb: 'Solid kick motor — it threw New Horizons at Pluto.',
  },
};

const B = (
  id: string,
  name: string,
  engine: string,
  engineCount: number,
  dryT: number,
  propT: number,
  heritage: string,
  visual: StageSpec['visual'],
): StageSpec => ({
  id,
  name,
  engine: ENGINES[engine],
  engineCount,
  dryMass: dryT * 1000,
  propMass: propT * 1000,
  heritage,
  visual,
});

// Visual dims are real published figures (diameter × stage length, m).
export const STAGE_PRESETS: Record<string, StageSpec> = Object.fromEntries(
  [
    // ── Boosters / first stages ──
    B('falcon9-s1', 'Falcon 9 first stage', 'merlin-1d', 9, 25.6, 411, 'SpaceX Falcon 9', { diameterM: 3.7, lengthM: 47, hull: 'white', gridFins: true, interstage: true }),
    B('superheavy', 'Super Heavy', 'raptor-2', 33, 200, 3400, 'SpaceX Starship', { diameterM: 9, lengthM: 71, hull: 'steel', gridFins: true }),
    B('saturn-v-s1c', 'Saturn V S-IC', 'f-1', 5, 130, 2160, 'Apollo / Saturn V', { diameterM: 10.1, lengthM: 42, hull: 'white', interstage: true }),
    B('atlas-v-ccb', 'Atlas V core (CCB)', 'rd-180', 1, 21.1, 284, 'ULA Atlas V', { diameterM: 3.8, lengthM: 32.5, hull: 'bronze' }),
    B('delta4-cbc', 'Delta IV core (CBC)', 'rs-68a', 1, 26.4, 204, 'ULA Delta IV', { diameterM: 5.1, lengthM: 40.8, hull: 'orange' }),
    B('ariane5-epc', 'Ariane 5 core (EPC)', 'vulcain-2', 1, 14.7, 170, 'Ariane 5', { diameterM: 5.4, lengthM: 30.5, hull: 'orange' }),
    B('sls-core', 'SLS core stage', 'rs-25', 4, 85.3, 987, 'NASA SLS / Artemis', { diameterM: 8.4, lengthM: 65, hull: 'orange' }),
    B('pslv-s139', 'PSLV first stage (S139)', 's139', 1, 30, 138, 'ISRO PSLV', { diameterM: 2.8, lengthM: 20, hull: 'white' }),
    B('angara-urm1', 'Angara URM-1', 'rd-191', 1, 10.6, 128, 'Angara A5', { diameterM: 2.9, lengthM: 25.1, hull: 'white' }),
    B('antares-s1', 'Antares first stage', 'nk-33', 2, 18.6, 242, 'Antares 100', { diameterM: 3.9, lengthM: 27.6, hull: 'white' }),
    B('new-glenn-s1', 'New Glenn first stage', 'be-4', 7, 100, 1050, 'Blue Origin New Glenn', { diameterM: 7, lengthM: 57.5, hull: 'white', interstage: true }),
    B('lm5-core', 'Long March 5 booster', 'yf-100', 2, 12, 135, 'CZ-5', { diameterM: 3.35, lengthM: 26.3, hull: 'white' }),
    B('electron-s1', 'Electron first stage', 'rutherford', 9, 0.95, 9.25, 'Rocket Lab Electron', { diameterM: 1.2, lengthM: 12.1, hull: 'black' }),
    B('shuttle-srb', 'Shuttle SRB', 'srb-shuttle', 1, 91, 500, 'Space Shuttle / SLS', { diameterM: 3.7, lengthM: 45.5, hull: 'white' }),
    // ── Upper stages ──
    B('falcon9-s2', 'Falcon 9 second stage', 'merlin-vac', 1, 4.0, 107.5, 'SpaceX Falcon 9', { diameterM: 3.7, lengthM: 13.8, hull: 'white' }),
    B('starship-ship', 'Starship (ship)', 'raptor-vac', 3, 100, 1200, 'SpaceX Starship', { diameterM: 9, lengthM: 52, hull: 'steel' }),
    B('saturn-v-s2', 'Saturn V S-II', 'j-2', 5, 40, 456, 'Apollo / Saturn V', { diameterM: 10.1, lengthM: 24.9, hull: 'white' }),
    B('saturn-v-s4b', 'Saturn V S-IVB', 'j-2', 1, 13.5, 109.5, 'Apollo / Saturn V', { diameterM: 6.6, lengthM: 17.8, hull: 'white' }),
    B('centaur-iii', 'Centaur III', 'rl10b-2', 1, 2.3, 20.8, 'Atlas V', { diameterM: 3.05, lengthM: 12.7, hull: 'steel' }),
    B('dcss-5m', 'Delta Cryogenic Second Stage', 'rl10b-2', 1, 3.5, 27.2, 'Delta IV', { diameterM: 5.1, lengthM: 13.7, hull: 'orange' }),
    B('ariane5-esca', 'Ariane 5 ESC-A', 'hm7b', 1, 4.5, 14.9, 'Ariane 5 ECA', { diameterM: 5.4, lengthM: 4.7, hull: 'white' }),
    B('pslv-ps2', 'PSLV second stage (Vikas)', 'vikas', 1, 5.3, 42, 'ISRO PSLV', { diameterM: 2.8, lengthM: 12.8, hull: 'white' }),
    B('lvm3-c25', 'LVM3 cryo stage (C25)', 'ce-20', 1, 5.0, 28, 'ISRO LVM3 / Chandrayaan-3', { diameterM: 4, lengthM: 13.5, hull: 'white' }),
    B('electron-s2', 'Electron second stage', 'rutherford-vac', 1, 0.25, 2.05, 'Rocket Lab Electron', { diameterM: 1.2, lengthM: 2.4, hull: 'black' }),
    B('falcon1-s2', 'Falcon 1 second stage', 'kestrel', 1, 0.36, 3.38, 'SpaceX Falcon 1', { diameterM: 1.7, lengthM: 5.5, hull: 'white' }),
    B('star48-kick', 'Star 48B kick stage', 'star-48b', 1, 0.13, 2.01, 'PAM-D / New Horizons', { diameterM: 1.24, lengthM: 2, hull: 'steel' }),
  ].map((s) => [s.id, s]),
);

export const PAYLOADS: Record<string, PayloadSpec> = {
  'cubesat-3u': {
    id: 'cubesat-3u',
    name: 'StudySat 3U CubeSat',
    type: 'cubesat',
    mass: 4,
    target: { altitude: 400e3, inclinationDeg: 28.5, label: 'LEO 400 km' },
    blurb: 'A shoebox-sized student satellite. Cheap ride to low orbit.',
  },
  'imaging-150': {
    id: 'imaging-150',
    name: 'HawkEye Imaging Sat',
    type: 'imaging',
    mass: 150,
    target: { altitude: 550e3, inclinationDeg: 53, label: 'LEO 550 km' },
    blurb: 'Takes pictures of Earth. Wants a higher orbit for a wider view.',
  },
  'weather-900': {
    id: 'weather-900',
    name: 'StormWatch Weather Sat',
    type: 'weather',
    mass: 900,
    target: { altitude: 800e3, inclinationDeg: 98.6, label: 'Sun-sync 800 km' },
    blurb: 'Watches storms from a sun-synchronous orbit — heavy and high.',
  },
};

export const FAIRING_STD: Fairing = {
  mass: 1_750,
  dragArea: 2.0,
  jettisonAltitude: 110e3,
};

/** Default winnable stack: Falcon 9 + imaging sat. */
export function defaultDesign(): RocketDesign {
  return {
    stages: [STAGE_PRESETS['falcon9-s1'], STAGE_PRESETS['falcon9-s2']],
    payload: PAYLOADS['imaging-150'],
    fairing: FAIRING_STD,
    refArea: 10.8, // ~3.7 m diameter core
    dragCoefficient: 0.4,
    qMax: Q_MAX_DEFAULT,
  };
}
